from typing import Literal, Optional, Sequence, Union

Cell = Union[str, int, float, None]
"""What a spreadsheet or database column actually hands you."""

Reason = Literal["empty", "non_numeric", "too_short", "too_long"]
Encoding = Literal["GTIN-8", "GTIN-12", "GTIN-13", "GTIN-14"]
Allocation = Literal[
    "restricted_circulation_company",
    "restricted_circulation_region",
    "company_prefix",
    "upc_company_prefix",
    "reserved_gs1_us",
    "unused_for_gtin8",
    "gtin8_issuance",
    "epc_general_manager",
    "demonstration",
    "issn",
    "isbn",
    "ismn",
    "refund_receipt",
    "coupon",
    "reserved_coupon",
    "reserved_future_use",
]

DOMAIN_MIN_DIGITS: int
DOMAIN_MAX_DIGITS: int

class Gtin14:
    """A GTIN in canonical GTIN-14 form. Check digit preserved, not verified."""

    @property
    def value(self) -> str: ...
    @property
    def shortest(self) -> str: ...
    @property
    def encoding(self) -> Encoding: ...
    @property
    def significant_digits(self) -> int: ...
    @property
    def check_digit(self) -> int: ...
    @property
    def expected_check_digit(self) -> int: ...
    @property
    def check_digit_is_valid(self) -> bool: ...
    @property
    def indicator(self) -> Optional[Literal["grouping", "variable_measure"]]: ...
    @property
    def indicator_digit(self) -> Optional[int]: ...
    @property
    def allocation(self) -> Allocation: ...
    @property
    def allocation_description(self) -> str: ...
    @property
    def is_restricted_circulation(self) -> bool: ...
    @property
    def is_publication_or_coupon(self) -> bool: ...
    @property
    def looks_like_internal_code(self) -> bool: ...
    @property
    def measure_field_looks_zeroed(self) -> bool: ...
    def key(self) -> GtinKey: ...
    def with_recomputed_check_digit(self) -> Gtin14: ...
    def __str__(self) -> str: ...

class GtinKey:
    """A match key. Not a GTIN, and deliberately hard to turn into one.

    There is no ``__str__``: ``str(key)`` and ``f"{key}"`` both give
    ``GtinKey('07390525907740')``. Use ``as_key_str()`` when you genuinely
    want the digits, so the call site says what it is writing.
    """

    def as_key_str(self) -> str: ...

class Parsed:
    """The result of reading one cell."""

    @property
    def raw(self) -> str: ...
    @property
    def gtin(self) -> Optional[Gtin14]: ...
    @property
    def reason(self) -> Optional[Reason]: ...
    @property
    def message(self) -> Optional[str]: ...
    @property
    def digits(self) -> Optional[int]: ...
    @property
    def store_form(self) -> str: ...
    @property
    def is_gtin(self) -> bool: ...
    @property
    def was_cleaned(self) -> bool: ...
    @property
    def removed_whitespace(self) -> bool: ...
    @property
    def removed_separators(self) -> bool: ...
    @property
    def dropped_fraction(self) -> bool: ...
    def key(self) -> Optional[GtinKey]: ...

def parse(value: Cell) -> Parsed: ...
def store_form(value: Cell) -> str: ...
def key(value: Cell) -> Optional[GtinKey]: ...
def parse_many(values: Sequence[Cell]) -> list[Parsed]: ...
def store_form_many(values: Sequence[Cell]) -> list[str]: ...
def key_strings(values: Sequence[Cell]) -> list[Optional[str]]: ...
